# Generated by Django 6.0.6 on 2026-07-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sync_cartorderitems_price_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
