# Generated by Django 6.0.6 on 2026-07-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cartorderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
    ]
