# Generated by Django 6.0.6 on 2026-07-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cartorderitems_coupons_cartorderitems_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('Draft', 'Draft'), ('Course Published', 'Course Published'), ('New Course Question', 'New Course Question'), ('Course Enrollement Completed', 'Course Enrollement Completed')], max_length=1000, null=True),
        ),
    ]
