# Generated by Django 4.2.7 on 2026-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_enrolledcourse_course_item_order_item'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='course',
                    name='language',
                    field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian')], default='English', max_length=20),
                ),
                migrations.AlterField(
                    model_name='course',
                    name='level',
                    field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
                ),
                migrations.AlterField(
                    model_name='course',
                    name='platform_status',
                    field=models.CharField(choices=[('Review', 'Review'), ('Disabled', 'Disabled'), ('Published', 'Published'), ('Draft', 'Draft'), ('Rejected', 'Rejected')], default='Published', max_length=20),
                ),
                migrations.AlterField(
                    model_name='course',
                    name='teacher_course_status',
                    field=models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Published', 'Published')], default='Published', max_length=20),
                ),
            ],
        ),
    ]
