# Generated by Django 5.2.16 on 2026-08-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_course_language_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Swahili', 'Swahili')], default='English', max_length=20),
        ),
    ]
