# Generated by Django 5.2.16 on 2026-08-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='student',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('New Review', 'New Review'), ('Draft', 'Draft'), ('Course Published', 'Course Published'), ('New Course Question', 'New Course Question'), ('Course Enrollement Completed', 'Course Enrollement Completed')], max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
