# Generated by Django 5.2.16 on 2026-08-27 18:43, hand-adjusted to rename
# CompletedCourse -> LessonProgress in place (preserving existing rows)
# instead of dropping and recreating the table.

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_cartorder_coupons_remove_cartorder_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['order', 'date']},
        ),
        migrations.AlterModelOptions(
            name='variantitem',
            options={'ordering': ['order', 'date']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        # Rename in place so the 3 pre-existing rows (and any FKs) survive.
        migrations.RenameModel(
            old_name='CompletedCourse',
            new_name='LessonProgress',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='current_position',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='max_watched_position',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completion_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            # Pre-existing rows only ever existed to mean "completed" under the
            # old CompletedCourse semantics, so they backfill to True here;
            # preserve_default=False means new rows use the model's real
            # default of False (in-progress until the watch threshold is met).
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_watched_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Lesson progress'},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'variant_item')},
        ),
        migrations.CreateModel(
            name='VideoUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=12, max_length=24, prefix='', unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_size', models.BigIntegerField()),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Uploading', 'Uploading'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Uploading', max_length=20)),
                ('temp_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='api.variantitem')),
            ],
        ),
    ]
