# Generated by Django 5.2.16 on 2026-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_backfill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
