# Generated by Django 5.2.16 on 2026-08-28 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fix_admin_log_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson-materials/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.variantitem')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
