# Generated by Django 5.2.16 on 2026-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_certificate_unique_per_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Code Switching', 'Code Switching'), ('French', 'French'), ('Swahili', 'Swahili')], default='English', max_length=20),
        ),
    ]
