# Generated by Django 5.2.16 on 2026-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_role_academy_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'SysAdmin'), ('Academy Admin', 'Academy Admin')], default='Student', max_length=20),
        ),
    ]
