# Generated by Django 5.2.16 on 2026-08-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_learning_enabled', models.BooleanField(default=True)),
                ('lesson_completion_threshold', models.PositiveIntegerField(default=90, help_text="Percentage of a lesson's duration a student must watch before it counts as completed.")),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
